mangaface:
  fragment_path_format: mangaface/<resourse::dir>/fragments/<fragment::dir>/<color::dir>/<shape_name>.png
  icon_path_format: mangaface/<resourse::dir>/icons/<shape_name>.gif
  default_color_dir: default
  _default_fragment: &frag
    dir: default
    priority: 100
    position:
      top: 0
      left: 0
  _color_set:
    skin: &skin_colors
      - dir: plain
        code: '#fabe9f'
      - dir: dark
        code: '#e0a182'
      - dir: light
        code: '#f9d5c3'
    hair: &hair_colors
      - dir: black
        code: '#262624'
      - dir: brown
        code: '#a87c4f'
      - dir: red
        code: '#ac3831'
      - dir: blondd
        code: '#fabe48'
    eye: &eye_colors
      - dir: black
        code: '#262624'
      - dir: brown
        code: '#a35d02'
      - dir: hazel
        code: '#d1c50b'
      - dir: green
        code: '#0dc438'
      - dir: blue
        code: '#1c71f1'
      - dir: gray
        code: '#a5caf3'
    cloth: &cloth_colors
      - dir: white
        code: '#f5f4e8'
      - dir: black
        code: '#262624'
      - dir: brown
        code: '#5b3b26'
      - dir: yellow
        code: '#dfa915'
      - dir: blue
        code: '#2f7faf'
      - dir: violet
        code: '#6854a2'
      - dir: red
        code: '#a91a26'
      - dir: green
        code: '#136f36'

  # TODO body shape
  fragments:
    - dir: body_shape
      permanent: true
      priority: 210
      position:
        top: 134
        left: 26

  resources:
    head:
      shape:
        id: 1000
        dir: head_shape
        colors: *skin_colors
        filename_range:
          min: 1
          max: 30
        fragments:
          - <<: *frag
            priority: 410
            position:
              top: 0
              left: 30

      ears:
        id: 1001
        dir: ear
        colors: *skin_colors
        filename_range:
          min: 1
          max: 6
        fragments:
          - <<: *frag
            dir: left_ear
            priority: 400
            color_inheritance: 1000
            position:
              top: 64
              left: 137
          - <<: *frag
            dir: right_ear
            priority: 400
            position:
              top: 64
              left: 12

      eyebrows:
        id: 1002
        dir: eyebrow
        colors: *hair_colors
        filename_range:
          min: 1
          max: 27
        movement_limit: 2
        fragments:
          - <<: *frag
            dir: left_eyebrow
            priority: 480
            position:
              top: 52
              left: 93
          - <<: *frag
            dir: right_eyebrow
            priority: 480
            position:
              top: 52
              left: 39
          - <<: *frag
            dir: left_eyeshadow
            priority: 460
            position:
              top: 55
              left: 91
          - <<: *frag
            dir: right_eyeshadow
            priority: 460
            position:
              top: 55
              left: 38

      eyes:
        id: 1003
        dir: eye
        colors: *eye_colors
        filename_range:
          min: 1
          max: 28
        fragments:
          - <<: *frag
            dir: left_eye
            priority: 470
            position:
              top: 68
              left: 97
          - <<: *frag
            dir: right_eye
            priority: 470
            position:
              top: 68
              left: 41

      nose:
        id: 1004
        dir: nose
        colors: *skin_colors
        filename_range:
          min: 1
          max: 34
        movement_limit: 2
        fragments:
          - <<: *frag
            priority: 450
            position:
              top: 68
              left: 65

      mouth:
        id: 1005
        dir: mouth
        colors: *skin_colors
        filename_range:
          min: 1
          max: 23
        movement_limit: 2
        fragments:
          - <<: *frag
            priority: 430
            position:
              top: 107
              left: 52

      mustache:
        id: 1006
        dir: mustache
        colors: *hair_colors
        filename_range:
          min: 1
          max: 29
        movement_limit: 2
        fragments:
          - <<: *frag
            priority: 440
            position:
              top: 104
              left: 49

      beard:
        id: 1007
        dir: beard_style
        colors: *hair_colors
        filename_range:
          min: 1
          max: 2
        fragments:
          - <<: *frag
            priority: 420
            position:
              top: 75
              left: 30

    hair:
      hair:
        id: 1008
        dir: hair_style
        colors: *hair_colors
        filename_range:
          min: 1
          max: 62
        rules:
          - match: [33, 37, 38, 39, 41, 43, 44, 60, 62] # Covered hairs
            force:
              1001: 0 # Remove 'ears'
        fragments:
          - <<: *frag
            dir: hair_front
            priority: 600
            position:
              top: 0
              left: 0
          - <<: *frag
            dir: hair_back
            priority: 200
            position:
              top: 23
              left: 0

    wearables:
      shirts:
        id: 1009
        dir: shirt
        colors: *cloth_colors
        filename_range:
          min: 1
          max: 25
        fragments:
          - <<: *frag
            priority: 300
            position:
              top: 124
              left: 26

      jackets:
        id: 1010
        dir: jacket
        colors: *cloth_colors
        filename_range:
          min: 1
          max: 19
        fragments:
          - <<: *frag
            priority: 310
            position:
              top: 122
              left: 24

      scarfs:
        id: 1011
        dir: scarf
        colors: *cloth_colors
        filename_range:
          min: 1
          max: 2
        fragments:
          - <<: *frag
            priority: 320
            position:
              top: 126
              left: 30

      hats:
        id: 1012
        dir: hat
        colors: *cloth_colors
        filename_range:
          min: 1
          max: 11
        movement_limit: 3
        rules:
          - match: [4, 6] # Swim caps
            force:
              1001: 0 # Remove 'ears'
              1008: 0 # Remove 'hair'
          - match: [1, 3, 5, 7, 8, 9, 10, 11] # Covered hats
            while:
              1008: [4, 5, 6, 7, 8, 12, 13, 14, 15, 16, 20, 24, 25, 29, 31, 44, 56, 57, 60] # Very long hairs
            force:
              1008: 22 # Bald style hair
        fragments:
          - <<: *frag
            priority: 700
            position:
              top: -20
              left: 0

      glasses:
        id: 1013
        dir: glasses
        filename_range:
          min: 1
          max: 34
        movement_limit: 2
        fragments:
          - <<: *frag
            priority: 500
            position:
              top: 57
              left: 27

    backgrounds:
      filled:
        id: 1014
        dir: bg_color
        filename_range:
          min: 1
          max: 24
        fragments:
          - <<: *frag
            priority: 100

      patterns:
        id: 1015
        dir: bg_pattern
        colors: *cloth_colors
        filename_range:
          min: 1
          max: 32
        fragments:
          - <<: *frag
            priority: 110

      themes:
        id: 1016
        dir: bg_theme
        filename_range:
          min: 1
          max: 18
        fragments:
          - <<: *frag
            priority: 120

    effects:
      weather:
        id: 1017
        dir: weather_effect
        filename_range:
          min: 1
          max: 1
        fragments:
          - <<: *frag
            priority: 800
