metadata:
  pack_label: manga_male_pack
  initializer_script: initializer_script


_anchors:
  _color_palettes:
    # Skin colors
    _skin_colors: &skin_colors
      - value: plain
        preview_color_code: '#fabe9f'
      - value: dark
        preview_color_code: '#e0a182'
      - value: light
        preview_color_code: '#f9d5c3'
    
    # Hair colors
    _hair_colors: &hair_colors
      - value: black
        preview_color_code: '#262624'
      - value: brown
        preview_color_code: '#a87c4f'
      - value: red
        preview_color_code: '#ac3831'
      - value: blonde
        preview_color_code: '#fabe48'
    
    # Eye colors
    _eye_colors: &eye_colors
      - value: black
        preview_color_code: '#262624'
      - value: brown
        preview_color_code: '#a35d02'
      - value: hazel
        preview_color_code: '#d1c50b'
      - value: green
        preview_color_code: '#0dc438'
      - value: blue
        preview_color_code: '#1c71f1'
      - value: gray
        preview_color_code: '#a5caf3'

    # Cloth colors
    _cloth_colors: &cloth_colors
      - value: white
        preview_color_code: '#f5f4e8'
      - value: black
        preview_color_code: '#262624'
      - value: brown
        preview_color_code: '#5b3b26'
      - value: yellow
        preview_color_code: '#dfa915'
      - value: blue
        preview_color_code: '#2f7faf'
      - value: violet
        preview_color_code: '#6854a2'
      - value: red
        preview_color_code: '#a91a26'
      - value: green
        preview_color_code: '#136f36'


navigators:
  - cover_url: <BASE_URL>/manga_male_pack/interface/head_section.png
    options:
      - title: Shape
        command: draw_head_shape_command
      - title: Ears
        command: draw_ears_command
      - title: Eyebrows
        command: draw_eyebrows_command
      - title: Eyes
        command: draw_eyes_command
      - title: Nose
        command: draw_nose_command
      - title: Mouth
        command: draw_mouth_command
      - title: Mustache
        command: draw_mustache_command
      - title: Beard
        command: draw_beard_command
  - cover_url: <BASE_URL>/manga_male_pack/interface/hair_section.png
    options:
      - title: Hair
        command: draw_hair_command
  - cover_url: <BASE_URL>/manga_male_pack/interface/wearables_section.png
    options:
      - title: Shirt
        command: draw_shirt_command
      - title: Jacket
        command: draw_jacket_command
      - title: Scarf
        command: draw_scarf_command
      - title: Hat
        command: draw_hat_command
      - title: Glasses
        command: draw_glasses_command
  - cover_url: <BASE_URL>/manga_male_pack/interface/backgrounds_section.png
    options:
      - title: Filled Background
        command: draw_filled_background_command
      - title: Patterns
        command: draw_patterns_command
      - title: Themes
        command: draw_themes_command
  - cover_url: <BASE_URL>/manga_male_pack/interface/effects_section.png
    options:
      - title: Weather Effect
        command: draw_weather_effect_command


scripts:
  - label: initializer_script
    description: Initializes a default face.
    jobs:
      - command: draw_body_shape_command
        item: 1
        color: plain

      - command: draw_head_shape_command
        item: 1
        color: plain

      - command: draw_ears_command
        item: 1
        color: plain

      - command: draw_eyebrows_command
        item: 1
        color: plain

      - command: draw_eyes_command
        item: 1
        color: black

      - command: draw_nose_command
        item: 1
        color: plain

      - command: draw_mouth_command
        item: 1
        color: plain

      - command: draw_shirt_command
        item: 1
        color: white

      - command: draw_filled_background_command
        item: 1


commands:
  - label: draw_body_shape_command
    items_count: 1
    item_preview_url: ''
    protected: true
    subscribed_layers:
      - body_shape_layer
  - label: draw_head_shape_command
    items_count: 30
    colors: *skin_colors
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/head_shapes/<ITEM>.gif
    protected: true
    subscribed_layers:
      - head_shape_layer
  - label: draw_ears_command
    items_count: 6
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/ears/<ITEM>.gif
    subscribed_layers:
      - left_ear_layer
      - right_ear_layer
  - label: draw_eyebrows_command
    items_count: 27
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/eyebrows/<ITEM>.gif
    movement_limit: 2
    subscribed_layers:
      - left_eyebrow_layer
      - right_eyebrow_layer
      - left_eyeshadow_layer
      - right_eyeshadow_layer
  - label: draw_eyes_command
    items_count: 28
    colors: *eye_colors
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/eyes/<ITEM>.gif
    subscribed_layers:
      - left_eye_layer
      - right_eye_layer
  - label: draw_nose_command
    items_count: 34
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/nose_shapes/<ITEM>.gif
    movement_limit: 2
    subscribed_layers:
      - nose_layer
  - label: draw_mouth_command
    items_count: 23
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/mouth_shapes/<ITEM>.gif
    movement_limit: 2
    subscribed_layers:
      - mouth_layer
  - label: draw_mustache_command
    items_count: 29
    colors: *hair_colors
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/mustache_styles/<ITEM>.gif
    movement_limit: 2
    subscribed_layers:
      - mustache_layer
  - label: draw_beard_command
    items_count: 2
    colors: *hair_colors
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/beard_styles/<ITEM>.gif
    subscribed_layers:
      - beard_layer
  - label: draw_hair_command
    items_count: 62
    colors: *hair_colors
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/hair/<ITEM>.gif
    subscribed_layers:
      - hair_front_layer
      - hair_back_layer
    rules:
        # Handle ear-covering hair styles
      - match_items_count: [33, 37, 38, 39, 41, 43, 44, 60, 62]
        force_layers:
            # Hide the left ear
          - layer: left_ear_layer
            item: 0
            # Hide the right ear
          - layer: right_ear_layer
            item: 0
  - label: draw_shirt_command
    items_count: 25
    colors: *cloth_colors
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/shirts/<ITEM>.gif
    subscribed_layers:
      - shirt_layer
  - label: draw_jacket_command
    items_count: 19
    colors: *cloth_colors
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/jackets/<ITEM>.gif
    subscribed_layers:
      - jackets_layer
  - label: draw_scarf_command
    items_count: 2
    colors: *cloth_colors
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/scarfs/<ITEM>.gif
    subscribed_layers:
      - scarf_layer
  - label: draw_hat_command
    items_count: 11
    colors: *cloth_colors
    movement_limit: 3
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/hats/<ITEM>.gif
    subscribed_layers:
      - hat_layer
    rules:
        # Rule 1: Handle swim caps / head covers
      - match_items_count: [4, 6]
        force_layers:
            # Hide the left ear
          - layer: left_ear_layer
            item: 0
            # Hide the right ear
          - layer: right_ear_layer
            item: 0
            # Hide the hair
          - layer: hair_layer
            item: 0
        # Rule 2: Handle all the hats covering the hair
      - match_items_count: [1, 3, 5, 7, 8, 9, 10, 11]
        when:
            # When the hair style is long
          - layer: hair_layer
            match_items_count: [4, 5, 6, 7, 8, 12, 13, 14, 15, 16, 20, 24, 25, 29, 31, 44, 56, 57, 60]
        force_layers:
            # Change hair style to bald
          - layer: hair_layer
            item: 22
  - label: draw_glasses_command
    items_count: 34
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/glasses/<ITEM>.gif
    movement_limit: 2
    subscribed_layers:
      - glasses_layer
  - label: draw_filled_background_command
    items_count: 24
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/bg_colors/<ITEM>.gif
    subscribed_layers:
      - filled_background_layer
  - label: draw_patterns_command
    items_count: 32
    colors: *cloth_colors
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/bg_patterns/<ITEM>.gif
    subscribed_layers:
      - pattern_layer
  - label: draw_themes_command
    items_count: 18
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/bg_themes/<ITEM>.gif
    subscribed_layers:
      - theme_layer
  - label: draw_weather_effect_command
    items_count: 1
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/weather_effects/<ITEM>.gif
    subscribed_layers:
      - weather_effect_layer


layers:
  - label: filled_background_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/bg_color/default/<ITEM>.png
    position:
      top: 0
      left: 0

  - label: pattern_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/bg_pattern/<COLOR>/<ITEM>.png
    position:
      top: 0
      left: 0

  - label: theme_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/bg_theme/default/<ITEM>.png
    position:
      top: 0
      left: 0

  - label: body_shape_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/body_shape/<COLOR>/<ITEM>.png
    position:
      top: 134
      left: 26

  - label: hair_back_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/hair_back/<COLOR>/<ITEM>.png
    position:
      top: 23
      left: 0

  - label: shirt_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/shirt/<COLOR>/<ITEM>.png
    position:
      top: 124
      left: 26

  - label: jackets_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/jacket/<COLOR>/<ITEM>.png
    position:
      top: 122
      left: 24

  - label: scarf_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/scarf/<COLOR>/<ITEM>.png
    position:
      top: 126
      left: 30

  - label: right_ear_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/right_ear/<COLOR>/<ITEM>.png
    position:
      top: 64
      left: 12

  - label: left_ear_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/left_ear/<COLOR>/<ITEM>.png
    position:
      top: 64
      left: 137

  - label: head_shape_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/head_shape/<COLOR>/<ITEM>.png
    position:
      top: 0
      left: 30

  - label: beard_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/beard/<COLOR>/<ITEM>.png
    position:
      top: 75
      left: 30

  - label: mouth_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/mouth/<COLOR>/<ITEM>.png
    position:
      top: 107
      left: 52

  - label: mustache_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/mustache/<COLOR>/<ITEM>.png
    position:
      top: 104
      left: 49

  - label: nose_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/nose/<COLOR>/<ITEM>.png
    position:
      top: 68
      left: 65

  - label: left_eyeshadow
    asset_url: <BASE_URL>/manga_male_pack/shapes/left_eyeshadow/<COLOR>/<ITEM>.png
    position:
      top: 55
      left: 91

  - label: right_eyeshadow
    asset_url: <BASE_URL>/manga_male_pack/shapes/right_eyeshadow/<COLOR>/<ITEM>.png
    position:
      top: 55
      left: 38

  - label: left_eye_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/left_eye/<COLOR>/<ITEM>.png
    position:
      top: 68
      left: 97

  - label: right_eye_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/right_eye/<COLOR>/<ITEM>.png
    position:
      top: 68
      left: 41

  - label: left_eyebrow
    asset_url: <BASE_URL>/manga_male_pack/shapes/left_eyebrow/<COLOR>/<ITEM>.png
    position:
      top: 52
      left: 93

  - label: right_eyebrow
    asset_url: <BASE_URL>/manga_male_pack/shapes/right_eyebrow/<COLOR>/<ITEM>.png
    position:
      top: 52
      left: 39

  - label: glasses_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/glasses/default/<ITEM>.png
    position:
      top: 57
      left: 27

  - label: hair_front_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/hair_front/<COLOR>/<ITEM>.png
    position:
      top: 0
      left: 0

  - label: hat_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/hat/<COLOR>/<ITEM>.png
    position:
      top: -20
      left: 0

  - label: weather_effect_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/weather_effect/default/<ITEM>.png
    position:
      top: 0
      left: 0
