pack_label: manga_male_pack
shape_path: <pack_label>/shapes/<resourse::dir>/<color::dir>/<shape_name>.png
default_color_dir: default

interface:
  sections:
    - label: head
      cover_url: <BASE_URL>/manga_male_pack/interface/head_section.png
      designers:
        - label: shape
          command_name: draw_head
          preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/head_shapes/<OPTION>.gif
        - label: ears
          command_name: draw_ears
          preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/ears/<OPTION>.gif
        - label: eyebrows
          command_name: draw_eyebrows
          preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/eyebrows/<OPTION>.gif
        - label: eyes
          command_name: draw_eyes
          preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/eyes/<OPTION>.gif
        - label: nose
          command_name: draw_nose
          preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/nose_shapes/<OPTION>.gif
        - label: mouth
          command_name: draw_mouth
          preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/mouth_shapes/<OPTION>.gif
        - label: mustache
          command_name: draw_mustache
          preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/mustache_styles/<OPTION>.gif
        - label: beard
          command_name: draw_beard
          preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/beard_styles/<OPTION>.gif
    - label: hair
      cover_url: <BASE_URL>/manga_male_pack/interface/hair_section.png
      designers:
        - label: hair
          command_name: draw_hair
          preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/hair/<OPTION>.gif
    - label: wearables
      cover_url: <BASE_URL>/manga_male_pack/interface/wearables_section.png
      designers:
        - label: shirt
          command_name: draw_shirt
          preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/shirts/<OPTION>.gif
        - label: jacket
          command_name: draw_jacket
          preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/jackets/<OPTION>.gif
        - label: scarf
          command_name: draw_scarf
          preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/scarfs/<OPTION>.gif
        - label: hat
          command_name: draw_hat
          preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/hats/<OPTION>.gif
        - label: glasses
          command_name: draw_glasses
          preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/glasses/<OPTION>.gif
    - label: backgrounds
      cover_url: <BASE_URL>/manga_male_pack/interface/backgrounds_section.png
      designers:
        - label: filled_background
          command_name: draw_filled_background
          preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/bg_colors/<OPTION>.gif
        - label: patterns
          command_name: draw_patterns
          preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/bg_patterns/<OPTION>.gif
        - label: themes
          command_name: draw_themes
          preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/bg_themes/<OPTION>.gif
    - label: effects
      cover_url: <BASE_URL>/manga_male_pack/interface/effects_section.png
      designers:
        - label: weather_effect
          command_name: draw_weather_effect
          preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/weather_effects/<OPTION>.gif

color_palettes:
  skin: &skin_colors
    - dir: plain
      code: '#fabe9f'
    - dir: dark
      code: '#e0a182'
    - dir: light
      code: '#f9d5c3'
  hair: &hair_colors
    - dir: black
      code: '#262624'
    - dir: brown
      code: '#a87c4f'
    - dir: red
      code: '#ac3831'
    - dir: blondd
      code: '#fabe48'
  eye: &eye_colors
    - dir: black
      code: '#262624'
    - dir: brown
      code: '#a35d02'
    - dir: hazel
      code: '#d1c50b'
    - dir: green
      code: '#0dc438'
    - dir: blue
      code: '#1c71f1'
    - dir: gray
      code: '#a5caf3'
  cloth: &cloth_colors
    - dir: white
      code: '#f5f4e8'
    - dir: black
      code: '#262624'
    - dir: brown
      code: '#5b3b26'
    - dir: yellow
      code: '#dfa915'
    - dir: blue
      code: '#2f7faf'
    - dir: violet
      code: '#6854a2'
    - dir: red
      code: '#a91a26'
    - dir: green
      code: '#136f36'

commands:
  draw_head:
    items: 30
    color_palette: *skin_colors
    icons_dir: head_shapes
    subscribed_layers:
      - head_shape
  draw_ears:
    items: 6
    color_palette: *skin_colors
    icons_dir: ears
    subscribed_layers:
      - left_ear_layer
      - right_ear_layer
  draw_eyebrows:
    items: 27
    color_palette: *hair_colors
    icons_dir: eyebrows
    movement_limit: 2
    subscribed_layers:
      - left_eyebrow
      - right_eyebrow
      - left_eyeshadow
      - right_eyeshadow
  draw_eyes:
    items: 28
    color_palette: *eye_colors
    icons_dir: eyes
    subscribed_layers:
      - left_eye_layer
      - right_eye_layer
  draw_nose:
    items: 34
    color_palette: *skin_colors
    icons_dir: noses
    movement_limit: 2
    subscribed_layers:
      - nose_layer
  draw_mouth:
    items: 23
    color_palette: *skin_colors
    icons_dir: mouth
    movement_limit: 2
    subscribed_layers:
      - mouth_layer
  draw_mustache:
    items: 29
    color_palette: *hair_colors
    icons_dir: mustache
    movement_limit: 2
  draw_beard:
    items: 2
    color_palette: *hair_colors
    icons_dir: beard_styles
  draw_hair:
    items: 62
    color_palette: *hair_colors
    icons_dir: hair_styles
    rules:
      - match: [33, 37, 38, 39, 41, 43, 44, 60, 62] # Covered hairs
        force:
          1001: 0 # Remove 'ears'
  draw_shirt:
    items: 25
    color_palette: *cloth_colors
    icons_dir: shirts
  draw_jacket:
    items: 19
    color_palette: *cloth_colors
    icons_dir: jackets
  draw_scarf:
    items: 2
    color_palette: *cloth_colors
    icons_dir: scarfs
  draw_hat:
    items: 11
    color_palette: *cloth_colors
    movement_limit: 3
    icons_dir: hats
    subscribed_layers:
      - hat_layer
    rules:
        # Rule 1: Handle swim caps / head covers
      - match_items: [4, 6]
        force_layers:
            # Hide the left ear
          - layer: left_ear_layer
            item: 0
            # Hide the right ear
          - layer: right_ear_layer
            item: 0
            # Hide the hair
          - layer: hair_layer
            item: 0
        # Rule 2: Handle all the hats covering the hair
      - match_items: [1, 3, 5, 7, 8, 9, 10, 11]
        when:
            # When the hair style is long
          - layer: hair_layer
            match_items: [4, 5, 6, 7, 8, 12, 13, 14, 15, 16, 20, 24, 25, 29, 31, 44, 56, 57, 60]
        force_layers:
            # Change hair style to bald
          - layer: hair_layer
            item: 22
  draw_glasses:
    items: 34
    icons_dir: glasses
    movement_limit: 2
  draw_filled_background:
    items: 24
    icons_dir: bg_colors
  draw_patterns:
    items: 32
    color_palette: *cloth_colors
    icons_dir: bg_patterns
  draw_themes:
    items: 18
    icons_dir: bg_themes
  draw_weather_effect:
    items: 1
    icons_dir: weather_effects

default_fragment: &frag
  dir: default
  priority: 100
  position:
    top: 0
    left: 0
  
layers_temp:
  left_eyebrow:
    dir: left_eyebrow
    priority: 480
    position:
      top: 52
      left: 93
  right_eyebrow:
    dir: right_eyebrow
    priority: 480
    position:
      top: 52
      left: 39
  left_eyeshadow:
    dir: left_eyeshadow
    priority: 460
    position:
      top: 55
      left: 91
  right_eyeshadow:
    dir: right_eyeshadow
    priority: 460
    position:
      top: 55
      left: 38

# TODO body shape
fragments:
  - dir: body_shapes
    permanent: true
    priority: 210
    position:
      top: 134
      left: 26

layers:
  - label: head_shape_layer
    icons_dir: head_shapes
    colors: *skin_colors
    priority: 410
    position:
      top: 0
      left: 30
  
  # Layers for ears
  - label: left_ear_layer
    icons_dir: left_ear
    priority: 400
    color_inheritance: 1000
    position:
      top: 64
      left: 137
  - label: right_ear_layer
    icons_dir: right_ear
    priority: 400
    position:
      top: 64
      left: 12

  # Layers for eyebrows
  - label: left_eyebrow
    dir: left_eyebrow
    priority: 480
    position:
      top: 52
      left: 93
  - label: right_eyebrow
    dir: right_eyebrow
    priority: 480
    position:
      top: 52
      left: 39
  - label: left_eyeshadow
    dir: left_eyeshadow
    priority: 460
    position:
      top: 55
      left: 91
  - label: right_eyeshadow
    dir: right_eyeshadow
    priority: 460
    position:
      top: 55
      left: 38

  # Layers for eyes
  - label: left_eye_layer
    dir: left_eye
    priority: 470
    position:
      top: 68
      left: 97
  - label: right_eye_layer
    dir: right_eye
    priority: 470
    position:
      top: 68
      left: 41

  - label: nose_layer
    priority: 450
    position:
      top: 68
      left: 65

  - label: mouth_layer
    priority: 430
    position:
      top: 107
      left: 52

  - label: mustache_layer
    icons_dir: mustache
    colors: *hair_colors
    filename_range:
      min: 1
      max: 29
    movement_limit: 2
    fragments:
      - <<: *frag
        priority: 440
        position:
          top: 104
          left: 49

  - label: beard_layer
    icons_dir: beard_styles
    colors: *hair_colors
    filename_range:
      min: 1
      max: 2
    fragments:
      - <<: *frag
        priority: 420
        position:
          top: 75
          left: 30
  
  - label: hair_layer
    icons_dir: hair_styles
    colors: *hair_colors
    filename_range:
      min: 1
      max: 62
    rules:
      - match: [33, 37, 38, 39, 41, 43, 44, 60, 62] # Covered hairs
        force:
          1001: 0 # Remove 'ears'
    fragments:
      - <<: *frag
        dir: hair_front
        priority: 600
        position:
          top: 0
          left: 0
      - <<: *frag
        dir: hair_back
        priority: 200
        position:
          top: 23
          left: 0
  
  - label: shirt_layer
    icons_dir: shirts
    colors: *cloth_colors
    filename_range:
      min: 1
      max: 25
    fragments:
      - <<: *frag
        priority: 300
        position:
          top: 124
          left: 26

  - label: jackets_layer
    icons_dir: jackets
    colors: *cloth_colors
    filename_range:
      min: 1
      max: 19
    fragments:
      - <<: *frag
        priority: 310
        position:
          top: 122
          left: 24

  - label: scarf_layer
    icons_dir: scarfs
    colors: *cloth_colors
    filename_range:
      min: 1
      max: 2
    fragments:
      - <<: *frag
        priority: 320
        position:
          top: 126
          left: 30
  
  - label: hat_layer
    icons_dir: hats
    colors: *cloth_colors
    filename_range:
      min: 1
      max: 11
    movement_limit: 3
    rules:
      - match: [4, 6] # Swim caps
        force:
          1001: 0 # Remove 'ears'
          1008: 0 # Remove 'hair'
      - match: [1, 3, 5, 7, 8, 9, 10, 11] # Covered hats
        while:
          1008: [4, 5, 6, 7, 8, 12, 13, 14, 15, 16, 20, 24, 25, 29, 31, 44, 56, 57, 60] # Very long hairs
        force:
          1008: 22 # Bald style hair
    fragments:
      - <<: *frag
        priority: 700
        position:
          top: -20
          left: 0
  - label: glasses_layer
    icons_dir: glasses
    filename_range:
      min: 1
      max: 34
    movement_limit: 2
    fragments:
      - <<: *frag
        priority: 500
        position:
          top: 57
          left: 27
  
  - label: filled_background_layer
    icons_dir: bg_colors
    filename_range:
      min: 1
      max: 24
    fragments:
      - <<: *frag
        priority: 100

  - label: patterns_layer
    icons_dir: bg_patterns
    colors: *cloth_colors
    filename_range:
      min: 1
      max: 32
    fragments:
      - <<: *frag
        priority: 110

  - label: theme_layer
    icons_dir: bg_themes
    filename_range:
      min: 1
      max: 18
    fragments:
      - <<: *frag
        priority: 120
  
  - label: weather_layer
    icons_dir: weather_effects
    filename_range:
      min: 1
      max: 1
    fragments:
      - <<: *frag
        priority: 800
