metadata:
  pack_name: manga_male_pack
  initializer_script: initializer_script


_anchors:
  _color_palettes:
    # Skin colors
    _skin_colors: &skin_colors
      - color: light
        preview_color_code: '#f9d5c3'
      - color: plain
        preview_color_code: '#fabe9f'
      - color: dark
        preview_color_code: '#e0a182'
    # Hair colors
    _hair_colors: &hair_colors
      - color: black
        preview_color_code: '#262624'
      - color: brown
        preview_color_code: '#a87c4f'
      - color: red
        preview_color_code: '#ac3831'
      - color: blonde
        preview_color_code: '#fabe48'
    # Eye colors
    _eye_colors: &eye_colors
      - color: black
        preview_color_code: '#262624'
      - color: brown
        preview_color_code: '#a35d02'
      - color: hazel
        preview_color_code: '#d1c50b'
      - color: green
        preview_color_code: '#0dc438'
      - color: blue
        preview_color_code: '#1c71f1'
      - color: gray
        preview_color_code: '#a5caf3'
    # Cloth colors
    _cloth_colors: &cloth_colors
      - color: white
        preview_color_code: '#f5f4e8'
      - color: black
        preview_color_code: '#262624'
      - color: brown
        preview_color_code: '#5b3b26'
      - color: yellow
        preview_color_code: '#dfa915'
      - color: blue
        preview_color_code: '#2f7faf'
      - color: violet
        preview_color_code: '#6854a2'
      - color: red
        preview_color_code: '#a91a26'
      - color: green
        preview_color_code: '#136f36'


navigators:
  # Head
  - cover_url: <BASE_URL>/manga_male_pack/interface/head_section.png
    options:
      - title: Shape
        command_name: draw_head_shape_command
      - title: Ears
        command_name: draw_ears_command
      - title: Eyebrows
        command_name: draw_eyebrows_command
      - title: Eyes
        command_name: draw_eyes_command
      - title: Nose
        command_name: draw_nose_command
      - title: Mouth
        command_name: draw_mouth_command
      - title: Mustache
        command_name: draw_mustache_command
      - title: Beard
        command_name: draw_beard_command
  # Hair
  - cover_url: <BASE_URL>/manga_male_pack/interface/hair_section.png
    options:
      - title: Hair
        command_name: draw_hair_command
  # Wearables
  - cover_url: <BASE_URL>/manga_male_pack/interface/wearables_section.png
    options:
      - title: Shirt
        command_name: draw_shirt_command
      - title: Jacket
        command_name: draw_jacket_command
      - title: Scarf
        command_name: draw_scarf_command
      - title: Hat
        command_name: draw_hat_command
      - title: Glasses
        command_name: draw_glasses_command
  # Backgrounds
  - cover_url: <BASE_URL>/manga_male_pack/interface/backgrounds_section.png
    options:
      - title: Filled Background
        command_name: draw_filled_background_command
      - title: Patterns
        command_name: draw_patterns_command
      - title: Themes
        command_name: draw_themes_command
  # Effects
  - cover_url: <BASE_URL>/manga_male_pack/interface/effects_section.png
    options:
      - title: Weather Effect
        command_name: draw_weather_effect_command


scripts:
  - name: initializer_script
    description: Initializes a default face.
    tasks:
      - command_name: draw_body_shape_command
        item_index: 1
        color: plain

      - command_name: draw_head_shape_commandd
        item_index: 1
        color: plain

      - command_name: draw_ears_command
        item_index: 1

      - command_name: draw_eyebrows_command
        item_index: 1
        color: black

      - command_name: draw_eyes_command
        item_index: 1
        color: black

      - command_name: draw_nose_command
        item_index: 1

      - command_name: draw_mouth_command
        item_index: 1

      - command_name: draw_shirt_command
        item_index: 1
        color: white

      - command_name: draw_filled_background_command
        item_index: 1


commands:
  # Draw body_shape
  - name: draw_body_shape_command
    item_count: 1
    item_preview_url: ''
    protected: true
    subscribed_layers:
      - body_shape_layer
  # Draw head_shape
  - name: draw_head_shape_command
    item_count: 30
    colors: *skin_colors
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/head_shapes/<ITEM>.gif
    protected: true
    subscribed_layers:
      - head_shape_layer
  # Draw ears
  - name: draw_ears_command
    item_count: 6
    color_dependency: draw_head_shape_command
    default_color: plain
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/ears/<ITEM>.gif
    subscribed_layers:
      - left_ear_layer
      - right_ear_layer
  # Draw eyebrows
  - name: draw_eyebrows_command
    item_count: 27
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/eyebrows/<ITEM>.gif
    movement_limit: 2
    color_dependency: draw_hair_command
    default_color: black
    subscribed_layers:
      - left_eyebrow_layer
      - right_eyebrow_layer
      - left_eyeshadow_layer
      - right_eyeshadow_layer
  # Draw eyes
  - name: draw_eyes_command
    item_count: 28
    colors: *eye_colors
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/eyes/<ITEM>.gif
    subscribed_layers:
      - left_eye_layer
      - right_eye_layer
  # Draw nose
  - name: draw_nose_command
    item_count: 34
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/nose_shapes/<ITEM>.gif
    movement_limit: 2
    color_dependency: draw_head_shape_command
    default_color: plain
    subscribed_layers:
      - nose_layer
  # Draw mouth
  - name: draw_mouth_command
    item_count: 23
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/mouth_shapes/<ITEM>.gif
    movement_limit: 2
    color_dependency: draw_head_shape_command
    default_color: plain
    subscribed_layers:
      - mouth_layer
  # Draw mustache
  - name: draw_mustache_command
    item_count: 29
    colors: *hair_colors
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/mustache_styles/<ITEM>.gif
    movement_limit: 2
    subscribed_layers:
      - mustache_layer
  # Draw beard
  - name: draw_beard_command
    item_count: 2
    colors: *hair_colors
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/beard_styles/<ITEM>.gif
    subscribed_layers:
      - beard_layer
  # Draw hair
  - name: draw_hair_command
    item_count: 62
    colors: *hair_colors
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/hair_styles/<ITEM>.gif
    subscribed_layers:
      - hair_front_layer
      - hair_back_layer
    rules:
        # Handle ear-covering hair styles
      - match_item_count: [33, 37, 38, 39, 41, 43, 44, 60, 62]
        force_layers:
            # Hide the left ear
          - layer: left_ear_layer
            item: 0
            # Hide the right ear
          - layer: right_ear_layer
            item: 0
  # Draw shirt
  - name: draw_shirt_command
    item_count: 25
    colors: *cloth_colors
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/shirts/<ITEM>.gif
    subscribed_layers:
      - shirt_layer
  # Draw jacket
  - name: draw_jacket_command
    item_count: 19
    colors: *cloth_colors
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/jackets/<ITEM>.gif
    subscribed_layers:
      - jackets_layer
  # Draw scarf
  - name: draw_scarf_command
    item_count: 2
    colors: *cloth_colors
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/scarfs/<ITEM>.gif
    subscribed_layers:
      - scarf_layer
  # Draw hat
  - name: draw_hat_command
    item_count: 11
    colors: *cloth_colors
    movement_limit: 3
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/hats/<ITEM>.gif
    subscribed_layers:
      - hat_layer
    rules:
        # Rule 1: Handle swim caps / head covers
      - match_item_count: [4, 6]
        force_layers:
            # Hide the left ear
          - layer: left_ear_layer
            item: 0
            # Hide the right ear
          - layer: right_ear_layer
            item: 0
            # Hide the hair
          - layer: hair_layer
            item: 0
        # Rule 2: Handle all the hats covering the hair
      - match_item_count: [1, 3, 5, 7, 8, 9, 10, 11]
        when:
            # When the hair style is long
          - layer: hair_layer
            match_item_count: [4, 5, 6, 7, 8, 12, 13, 14, 15, 16, 20, 24, 25, 29, 31, 44, 56, 57, 60]
        force_layers:
            # Change hair style to bald
          - layer: hair_layer
            item: 22
  # Draw glasses
  - name: draw_glasses_command
    item_count: 34
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/glasses/<ITEM>.gif
    movement_limit: 2
    subscribed_layers:
      - glasses_layer
  # Draw filled_background
  - name: draw_filled_background_command
    item_count: 24
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/bg_colors/<ITEM>.gif
    subscribed_layers:
      - filled_background_layer
  # Draw patterns
  - name: draw_patterns_command
    item_count: 32
    colors: *cloth_colors
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/bg_patterns/<ITEM>.gif
    subscribed_layers:
      - pattern_layer
  # Draw themes
  - name: draw_themes_command
    item_count: 18
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/bg_themes/<ITEM>.gif
    subscribed_layers:
      - theme_layer
  # Draw weather_effect
  - name: draw_weather_effect_command
    item_count: 1
    item_preview_url: <BASE_URL>/manga_male_pack/interface/design_preview/weather_effects/<ITEM>.gif
    subscribed_layers:
      - weather_effect_layer


layers:
  - name: filled_background_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/bg_color/default/<ITEM>.png
    position:
      top: 0
      left: 0

  - name: pattern_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/bg_pattern/<COLOR>/<ITEM>.png
    position:
      top: 0
      left: 0

  - name: theme_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/bg_theme/default/<ITEM>.png
    position:
      top: 0
      left: 0

  - name: body_shape_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/body_shape/<COLOR>/<ITEM>.png
    position:
      top: 134
      left: 26

  - name: hair_back_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/hair_back/<COLOR>/<ITEM>.png
    position:
      top: 23
      left: 0

  - name: shirt_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/shirt/<COLOR>/<ITEM>.png
    position:
      top: 124
      left: 26

  - name: jackets_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/jacket/<COLOR>/<ITEM>.png
    position:
      top: 122
      left: 24

  - name: scarf_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/scarf/<COLOR>/<ITEM>.png
    position:
      top: 126
      left: 30

  - name: right_ear_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/right_ear/<COLOR>/<ITEM>.png
    position:
      top: 64
      left: 12

  - name: left_ear_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/left_ear/<COLOR>/<ITEM>.png
    position:
      top: 64
      left: 137

  - name: head_shape_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/head_shape/<COLOR>/<ITEM>.png
    position:
      top: 0
      left: 30

  - name: beard_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/beard/<COLOR>/<ITEM>.png
    position:
      top: 75
      left: 30

  - name: mouth_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/mouth/<COLOR>/<ITEM>.png
    position:
      top: 107
      left: 52

  - name: mustache_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/mustache/<COLOR>/<ITEM>.png
    position:
      top: 104
      left: 49

  - name: nose_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/nose/<COLOR>/<ITEM>.png
    position:
      top: 68
      left: 65

  - name: left_eyeshadow_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/left_eyeshadow/<COLOR>/<ITEM>.png
    position:
      top: 55
      left: 91

  - name: right_eyeshadow_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/right_eyeshadow/<COLOR>/<ITEM>.png
    position:
      top: 55
      left: 38

  - name: left_eye_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/left_eye/<COLOR>/<ITEM>.png
    position:
      top: 68
      left: 97

  - name: right_eye_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/right_eye/<COLOR>/<ITEM>.png
    position:
      top: 68
      left: 41

  - name: left_eyebrow_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/left_eyebrow/<COLOR>/<ITEM>.png
    position:
      top: 52
      left: 93

  - name: right_eyebrow_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/right_eyebrow/<COLOR>/<ITEM>.png
    position:
      top: 52
      left: 39

  - name: glasses_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/glasses/default/<ITEM>.png
    position:
      top: 57
      left: 27

  - name: hair_front_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/hair_front/<COLOR>/<ITEM>.png
    position:
      top: 0
      left: 0

  - name: hat_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/hat/<COLOR>/<ITEM>.png
    position:
      top: -20
      left: 0

  - name: weather_effect_layer
    asset_url: <BASE_URL>/manga_male_pack/shapes/weather_effect/default/<ITEM>.png
    position:
      top: 0
      left: 0
