pack_label: sample_pack
default_fragment_dir: default
default_color_dir: default
fragment_path_format: sample_pack/<resourse_dir>/fragments/<fragment_dir>/<color_dir>/<shape_name>.png
icon_path_format: sample_pack/<resourse_dir>/icons/<shape_name>.gif
resources:
  sample_category_label_01:
    sample_resource_label_01:
      id: int # >=1000
      dir: string # sample_resource_directory_01
      colors:
        - dir: string # sample_color_directory_01
          code: string # '#fff'
      filename_range:
        min: int
        max: int
      movement_limit: int
      rules:
        - match: int[] # array of filenames
          while:
            1000: int[] # <resource id: array of filenames>
          force:
            1000: int # <resource id: filename>
      fragments:
        - dir: string # default / sample_fragment_directory_01
          priority: int # >=100
          color_inheritance: int # resource id (>=1000)
          position:
            top: int
            left: int
